name: Test

on:
  workflow_dispatch:
    inputs:
      triggered_by_release:
        type: boolean
        default: false
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
  merge_group:
    types: [synchronize, closed, checks_requested] # Trigger when pull request is synchronized or closed

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      triggered_by_release: ${{ steps.set_release_flag.outputs.triggered_by_release }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Load environment variables from .env file
        run: |
          cp .env.example .env

      - name: Run tests
        run: bun run test

      - name: Set Release Flag
        id: set_release_flag
        run: |
          echo "triggered_by_release=${{ github.event.inputs.triggered_by_release }}" >> $GITHUB_ENV
          echo "::set-output name=triggered_by_release::${{ github.event.inputs.triggered_by_release }}"
